services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    #配置文件启动
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    container_name: nginx
    command: nginx -g 'daemon off;'
    ports:
      - '80:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx